mdn/fred

build/ssr.js
components/bcd/index.js
components/color-theme/index.js
components/heading-anchor/index.js
components/reference-layout/index.js
entry.ssr.js
eslint.config.js
fluent.js
index.js
observatory/landing/index.js
observatory/results/cookies.js
observatory/results/csp.js
observatory/results/grade-svg.js
observatory/results/history.js
observatory/results/human-duration.js
observatory/results/index.js
observatory/results/rating.js
observatory/results/raw-headers.js
observatory/results/results.js
observatory/results/scoring.js
observatory/results/tabs.js
observatory/results/tooltip.js
observatory/utils.js
package-lock.json
package.json
pages/doc/index.js
pages/observatory/index.js
pages/settings/index.js
rsbuild.config.js
server.js

Adds `eslint-plugin-import`, but only enables `import/order` to group and order imports.

style(eslint): add eslint-plugin-import

---

build/ssr.js
eslint.config.js
fluent.js
observatory/results/grade-svg.js
observatory/results/rating.js
observatory/results/results.js
package-lock.json
package.json

Adds `eslint-plugin-jsdoc` and resolves all issues.

style(eslint): add eslint-plugin-jsdoc + fix issues

---

.github/workflows/test.yml
.stylelintrc.json
components/colors/index.css
components/fonts/index.css
components/footer/index.css
components/formal-syntax/index.css
components/index.css
components/menu/elements/panel.css
components/menu/elements/tabs.css
components/reference-toc/index.css
lefthook.yml
legacy/spinner/index.css
legacy/switch/index.css
observatory/results/index.css
package-lock.json
package.json

Adds `stylelint`, disable failing rules for now, and ignore one empty block.

style(stylelint): add stylelint

---

.github/workflows/_deploy.yml
.github/workflows/main-review-companion.yml

Automatically deploy `main` for to https://fred.review.mdn.allizom.net/, once per day, and on demand.
Primary entry-point for reviewing the state of fred.

ci(workflows): add main-review-companion

---

components/quick-search/index.js
components/site-search/index.js
components/site-search/types.d.ts
entry.client.js
entry.ssr.js
l10n/en-us.flt
l10n/fluent.js
package-lock.json
package.json
pages/search/index.js
server.js

allow basic html in all fluent strings
add proxy to staging api

basic site search

---

.gitignore
build/plugins/ts-nocheck.js
build/ssr.js
dist/ssr/index.d.ts
dist/ssr/package.json
eslint.config.js
rsbuild.config.js

Test build to ensure I didn't break anything

add types to ssr bundle and ensure tsc doesn't check file

---

components/breadcrumbs/index.css
components/breadcrumbs/index.js

enhance(breadcrumbs): convert to list

---

components/heading-anchor/index.js

fix: pass section titles through unescaped

fix: pass section titles through unescaped

---

components/color/index.css

Grays are already sorted like that. It helps to find the needed color.

Sort tinted colors from light to dark

---

components/code-example/syntax-highlight.js
components/color-theme/index.js
components/compat/index.js
components/content-feedback/index.js
components/copy-button/index.js
components/site-search/index.js
l10n/fluent.js
observatory/results/cookies.js
observatory/results/csp.js
observatory/results/grade-svg.js
observatory/results/history.js
observatory/results/human-duration.js
observatory/results/rating.js
observatory/results/raw-headers.js
observatory/results/scoring.js
observatory/results/tabs.js
observatory/results/tooltip.js
package-lock.json
package.json
server.js
symmetric-context/both.js
symmetric-context/client.js
symmetric-context/server.js
tsconfig.json

requires https://github.com/mdn/rari/pull/191 to merge

update tsconfig to require .js-suffixed imports

---

components/logo/index.css
components/quick-search/index.js

- Alter blue for light/dark scheme
- Fill icons with text color
- Fix input text font
- Remove unused icon class name

Fix header’s dark scheme colors

---

package-lock.json

looks like https://github.com/npm/cli/issues/4828 may have been the issue

regenerate package-lock.json to solve correct @rspack/binding not being installed

---

components/search-modal/element.css
components/search-modal/element.js

- Material design icon
- Better dark mode colors
- Higher contrast

Update search button design

---

rspack.config.js

fix new URL() issue and output esm for client

---

rspack.config.js

fix(rspack): add hash to chunk names to cache bust

---

build/hmr.js
entry.client.js
rspack.config.js

fix(rspack): don't load hmr in prod bundle

---

components/breadcrumbs/index.css
components/breadcrumbs/index.js

fix(breadcrumbs): ensure bar shows up everywhere

---

components/navigation/hook.js
components/navigation/index.js
entry.client.js

put hook within component, as they're tightly coupled: I think this should be an approved paradigm

fix(nav): make hamburger interactive

---

components/menu/desktop.css
components/menu/index.js
components/menu/mobile.css
components/navigation/desktop.css
components/navigation/mobile.css

Mobile menu now appears 130px later: 1136 → 1006

Use shorter label on desktop

---

components/breadcrumbs/index.js

fix(language-switcher): hydration error

---

components/menu/desktop.css

fix menu underlap #124

---

components/generic-content/index.css
components/generic-content/index.js
components/generic-doc/index.js
components/generic-layout/index.css
components/generic-layout/index.js
components/generic-sidebar/index.css
components/generic-sidebar/index.js
components/generic-toc/index.css
components/generic-toc/index.js
components/observatory-form/element.css
components/observatory-rescan-button/element.css
entry.ssr.js

Observatory docs (generic pages)

Observatory docs

---

components/code-example/common.css
components/code-example/element.css
components/code-example/element.js
components/code-example/global.css
components/content/index.css
components/copy-button/element.js
components/interactive-example/element.js
components/live-sample-result/element.css
components/live-sample-result/element.js
components/live-sample-result/global.css
components/play-controller/element.js
components/play-runner/element.js
components/playground/types.d.ts
entry.client.js
hooks/code-examples.js
hooks/live-samples.js
types/element-map.d.ts

feat: add live samples, improve code examples styling, simplify ix parsing logic

---

.github/workflows/_deploy.yml

Refines the list of pages built as part of the PR Review Companion.
1. Adds all menu pages (to avoid that clicking a menu item yields a 404).
2. Removes unnecessarily built pages (e.g. all Glossary pages).
```
Building everything 🛠️
Took:   45.493ms for reading 655 docs
Took:   21.813ms to build spas (14)
Took:     8.004s to build content docs (655)
Took:    6.560ms to build search index
Took:   16.028ms to build generic pages (11)
Took:   41.584ms to build curriculum pages (27)
Took:  169.249ms to build blog (64)
Took:    6.439ms to build contributor spotlights (12)
Took:    1.996ms to write sitemaps (783)
--- templ summary ---
```
```
Building everything 🛠️
Took:   10.084ms for reading 88 docs
Took:   22.522ms to build spas (14)
Took:     1.690s to build content docs (88)
Took: …
```

enhance(pr-review-companion): refine built pages

---

components/blog-post/server.css
components/blog-post/server.js
components/generic-layout/server.js
components/generic-toc/server.js
components/reference-layout/server.js
components/reference-toc/server.js

Moves the sidebars behind the respective content in DOM.
Improves accessibility, and find-in-page experience.

refactor(dom): update order (toc, content, sidebar)

---

components/play-controller/element.js
components/play-editor/element.js
components/playground/element.css
components/playground/element.js
components/playground/server.css
components/playground/server.js
components/playground/types.d.ts
components/playground/utils.js
entry.ssr.js
hooks/live-samples.js
types/element-map.d.ts

feat(playground): add initial support, no responsive, no share

---

components/play-runner/element.js
server.js
vendor/yari/libs/play/index.js

fixes clear-site-data header removing playground session locally
makes changes to the runner which need to be upstreamed to yari
run build to test this still works with the old runner code

fix(playground): run runner on a different port so it has a different origin

---

components/a11y-menu/server.css
components/a11y-menu/server.js
components/content/server.js
components/generic-content/server.js
components/navigation/server.js
components/page-layout/server.js

Adds a skip link menu for accessibility with two items:
- Skip to main content
- Skip to search
Parity with yari.

feat(a11y-menu): initial impl

---

components/footer/server.js

To avoid content outside of landmarks

Use footer landmark

---

components/color/background.css
components/color/border.css
components/color/global.css
components/color/text.css
components/global/global.css
components/ix-tab/element.css

- Uses number scale for grays
- Update values
- Use darker gray (05) for body

Update grays to use numbers

---

rspack.config.js

fix(rspack): ensure postcss is run on css imported from css

---

components/color/background.css
components/color/border.css
components/color/global.css
components/color/link.css
components/color/text.css
components/generic-sidebar/server.css
components/generic-toc/server.css
components/interactive-example/element.css
components/left-sidebar/server.css
components/logo/server.css
components/observatory/index.css
components/reference-toc/server.css
components/search-modal/element.css

- The middle color is now 50
- The whole range is 10, 20, 50, 80, 90

Use number suffixes for tinted colors

---

components/about-tabs/element.css

removed useless media query

---

components/color/global.css
components/color/scrollbar.css

- Uses more human-readable color values
- Attaches transparent colors to black/white ones

Use HSL and combine alpha colors

---

rspack.config.js
types/modules.d.ts

`import example from "./example.png?url";` will give a string with the path to the asset

feat(rspack): allow importing assets with `?url` suffix

---

.github/workflows/_deploy.yml
entry.client.js
hooks/glean-init.js
package-lock.json
package.json
rspack.config.js

Adds Glean with automatic page load, and automatic click events.
Depends on: https://github.com/mdn/yari/pull/13054

feat(telemetry): add Glean

---

components/color/scrollbar.css
components/generic-about/server.css
components/generic-community/server.css

- Uses color prefix for scrollbar colors
- Renames bg and color to track and thumb

Use color prefix for scrollbar colors

---

components/compat-table/element.js

see: https://github.com/mdn/yari/pull/13061

fix(bcd): limit length of long bcd tables

---

components/env/index.js
components/login-button/element.js
components/modal/element.css
components/modal/element.js
components/playground/element.css
components/playground/element.js
types/element-map.d.ts

testing I got the auth code right for the test environment

feat(playground): add sharing and loading shared playgrounds

---

.github/workflows/_deploy.yml
.github/workflows/main-review-companion.yml
.github/workflows/pr-review-companion.yml

Adds the French locale to the `main-review-companion`.

ci(main-review-companion): build French locale

---

components/content-section/README.md
components/content-section/server.css
components/table-container/global.css

Since it’s its own thing, even if it’s small.

refactor(content-section): split table-container into component

---

components/homepage-hero/server.css

- Uses a variable for font-size
- Sets the link color

refactor(homepage-hero): style links

---

components/footer/server.js

- Adds accessible labels to logos
- Refactors variable names

fix(footer): add labels to logos

---

.env-dist
.github/workflows/_deploy.yml
.gitignore
.npmignore
README.md
components/env/index.js
components/navigation/server.js
components/outer-layout/server.js
components/user/context.js
hooks/glean-init.js
package-lock.json
package.json
rspack.config.js
scripts/server.js
server.js

test the build
will merge as a push to main to preserve commit history

chore: various changes to support packaging for content

---

.github/workflows/npm-publish.yml
package-lock.json
package.json

chore(npm): add publish workflow

---

components/search-modal/element.css
components/search-modal/element.js

Styles the search modal.
It wasn't styled yet.

chore(search-modal): add styles

---

components/placement-sidebar/element.css
components/reference-layout/server.css

Add focus visible to placement so focus does not vanish. Add padding to make it look nice.

fix(placement): add focus-visible to sidebar

---

components/homepage-hero/server.js
l10n/en-US.ftl

Only links should be underlined

fix(homepage-hero): avoid non-link underline

---

components/homepage-header/server.js
components/menu/server.js

- Lost closing tag
- A bunch of unnecessary sections

fix(menu, homepage): fix validation errors

---

components/icon/menu.svg
components/menu/base.css
components/menu/desktop.css
components/menu/mobile.css
components/navigation/base.css
components/navigation/mobile.css
components/navigation/server.js
components/user-menu/base.css
components/user-menu/desktop.css
components/user-menu/element.css
components/user-menu/element.js
components/user-menu/links.js
components/user-menu/mobile.css
l10n/en-US.ftl

- Adds mobile styles
- Uses masked icons

feat(user-menu): add mobile styles

---

components/left-sidebar/server.css

fix(left-sidebar): use code font family

---

components/icon/arrow-left.svg
components/icon/arrow-right.svg
components/pagination/server.css
components/pagination/server.js

- Use mask arrows
- Simplify styling
- Add hovers, make the current item more prominent

refactor(pagination): use mask arrows, simplify styling

---

components/content-section/server.css
components/font/jetbrains-mono.css
components/not-found/element.css

No per-case adjustment, just the global one

enhance(font): make it smaller

---

components/color/global.css
components/global/global.css
components/html/global.css

- Add global link colors
- Move HTML styles into a separate component
- Keep the global component to a minimum that we need everywhere

feat(global): add global link colors

---

components/content-section/server.css
components/global/global.css
components/heading-anchor/server.css

- Set visited links only for content
- Improve heading anchor on smaller screens

enhance(heading-anchor): improve hash 

---

components/blog-index/server.js
components/blog-post/server.js
components/blog/utils.js

Image lazy loading on Blog imdex page
Optimization

enhance(blog): lazy load images "below the fold" on index page

---

components/menu/base.css
components/user-menu/base.css
components/user-menu/desktop.css
components/user-menu/element.css
components/user-menu/element.js
components/user-menu/mobile.css

- Style Log in link for mobile
- Use global styles
- Fix linting warning

enhance(user-menu): style mobile login link

---

components/dropdown/element.js

Allows closing dropdowns by pressing <kbd>Esc</kbd>.
Addresses a11y feedback.

enhance(dropdown): close on escape

---

.github/workflows/test.yml
.gitignore
.lefthook.yml
.vscode/.gitignore
.vscode/extensions.json
components/curriculum/utils.js
components/not-found/element.js
components/observatory-tests-and-scores/element.js
components/pagination/server.js
components/site-search/element.js
components/themed-image/element.js
components/user-menu/element.js
package-lock.json
package.json
tsconfig.json

Adds `@jackolope/lit-analyzer`, and runs it with lefthook in the `pre-commit` and `pre-push` hooks, and as part of the `test` workflow.
Improve our Lit code quality.

chore(deps-dev): add lit-analyzer

---

components/observatory-landing/server.js
components/observatory-results/server.js

Observatory skip links
A11y improvements

fix(obs): add skip links to content

---

components/color-theme/element.css
components/color-theme/element.js
components/language-switcher/element.css
components/language-switcher/element.js

fix(breadcrumbs-bar): show active value in dropdowns

---

components/content-section/server.css

feat(content-section): add # to dl anchors

---

components/content-section/server.css

Adds border, and sets color and spacing for `<blockquote>`s within content.
Parity with yari.

chore(content-section): style blockquote

---

components/curriculum/module-list.css

Increase card size to avoid scrolling
Before
After

fix(curriculum): increase card height to accommodate for larger font size

---

components/breadcrumbs-bar/server.js
components/generic-sidebar/server.js

| before | after |
| - | - |
| <img width="750" height="1334" alt="Screen Shot 2025-07-18 at 14 19 37" src="https://github.com/user-attachments/assets/0b61905e-3d74-4b42-aaea-4864d779a9cf" /> | <img width="750" height="1334" alt="Screen Shot 2025-07-18 at 14 19 40" src="https://github.com/user-attachments/assets/22181675-2eb4-4de6-b73c-001bcc6a611d" /> |

fix(toggle-sidebar): don't show when there's no sidebar
