mdn/fred

components/content/index.js, components/specifications-list/index.js
Adds a server-side `SpecificationsList()` component.
Implements the Specifications section.
| Yari | Fred |
|--------|--------|
| <img width="643" alt="image" src="https://github.com/user-attachments/assets/df031053-aa2a-48b6-90d4-ecc9d2933b92" /> | <img width="643" alt="image" src="https://github.com/user-attachments/assets/3fc3997b-0626-4a64-9c1e-1a2dad0fa4ad" /> |
=> feat(components): add Specifications list

.stylelintrc.json, components/button/index.css, components/button/index.js, components/index.css
Adds a functional `Button()` component.
Also:
- Updates the stylelint config to allow `--default` suffix for CSS variables.
Extracted from https://github.com/mdn/fred/pull/45.
=> feat(components): add functional Button

.gitignore
Given the instruction in the readme:
> 1. Copy `.env-dist` to `.env` and update
It would be right to ignore the local copy.
=> Ignore local .env file

components/breadcrumbs/index.css, components/breadcrumbs/index.js, components/color-theme/index.css
First pass at styling the breadcrumb bar - notable things
- Reviewed the site for greys and suggested 6 greys which should be global are in the component
- Styled a button for search use - agreed to keep the input but move the button code to the search component commented out incase we change our mind - `mdn-search`
- Search should stay in top part of header and removed from breadcrumb bar - theme, save & language in breadcrumb bar
- We will show breadcrumbs on every page
=> Breadcrumb styling & greys

build/server-worker.js, build/types.d.ts, rspack.config.js, server.js
should fix weird bugs with undoing changes locally
should also fix bugs where the global js state gets into a weird state
=> fix(dev): use worker to invalidate esm cache

components/page-layout/server.css
Otherwise, the grid will try to contain your blocks, and they won’t overflow.
See https://stackoverflow.com/a/52861514
=> Fix layout overflow

.github/workflows/main-review-companion.yml
Prevent deploy workflow running on `main` in forks.
When I sync my fork from upstream, the CI runs on `main`, which will fail.
- https://github.com/bsmth/fred/actions
=> ci(main-review-companion): exclude forks

components/reference-layout/server.js, components/translation-banner/server.js
Adds the `translation-banner` at the top of translated pages
Parity with yari.
=> feat(components): add translation-banner

components/button/element.js, components/button/pure.js, components/cookie/utils.js, components/language-always-redirect-button/element.js, components/language-switcher/element.css, components/language-switcher/element.js, components/preferred-locale/utils.js, components/switch/element.css, components/switch/element.js, components/translation-banner/server.css, components/translation-banner/server.js, types/element-map.d.ts
Adds the "Remember language" feature to the language switcher.
Also adds `en-US` shortcuts to the translation banner.
Parity with yari, and improved UX for users preferring `en-US` despite their browser indicating preference for another locale.
Included related changes:
- Adds the `switch` component, [based on ux-components](https://mdn.github.io/ux-components/pages/sandbox/index.html#switch).
- Adds the `cookie` utils component, [based on yari](https://github.com/mdn/yari/blob/5465a64478c25a19119f1d70152a20b318eae531/client/src/utils.ts#L166-L202).
- Adds the `preferred-locale` utils component, [based on yari](https://github.com/mdn/yari/blob/5465a64478c25a19119f1d70152a20b318eae531/client/src/ui/organisms/article-actions/language-menu/index.tsx#L144-L158).
- Adds the `target` property …
=> feat(language-switcher,translation-banner): add Remember language

components/breadcrumbs/server.js
Adds structured breadcrumbs data.
(Note: Also switches from `<ul>` to `<ol>`, because breadcrumbs _are_ ordered.)
Parity with yari, and SEO.
See: https://developers.google.com/search/docs/appearance/structured-data/breadcrumb#rdfa_1
Tested with: https://search.google.com/test/rich-results
=> chore(breadcrumbs): add structured data

components/favicon/pure.js, components/pagination/server.js
- Cleans up the snippet
- Fixes the double-icon download in Chrome
- Only SVG is downloaded now (like in Firefox)
- Safari still downloads both, oh well
=> refactor(favicon): update favicon snippet

components/advertising/server.css, components/advertising/server.js
Renamed the CSS classes
These tend to get falsely blocked by ad blockers.
=> fix: rename css classes on advertise with us page

components/content-section/server.css
No decoration for anchors. Needs to be further improved with the `self-link` class
=> fix(content-section): revert anchor styling

components/external-link/global.css
Added `vertical-align: middle`, otherwise non-empty `content` pushes it up
=> fix(external-link): icon alignment

components/blog-index/server.css, components/blog-index/server.js
- Add proper sizing for covers (1200 x 630)
- Set the height, use auto from the image
Before/after
https://github.com/user-attachments/assets/3935814a-7cd4-4bbd-9366-d0b9e85eb2f5
=> fix(blog): avoid page jumping on load

components/content-section/server.css
Updates styling for tables with the `.properties` class
Also updates styling for 'regular' tables in content to include zebra striping
=> chore(content-section): style tables including properties

components/breadcrumbs-bar/server.js
Shows the language switcher also on other pages.
Consistency: The language selector was previously only shown on doc pages.
Upstream:
- https://github.com/mdn/rari/pull/272
(Until that change has landed and is released, tsc will complain.)
=> enhance(breadcrumbs-bar): show language-switcher on non-Doc pages

components/site-search/element.css, components/site-search/element.js, components/site-search/types.d.ts, l10n/de.ftl, l10n/en-US.ftl
Implementing the suggestions when passed down from the search backend.
Parity with yari
Before:
After:
=> feat(site-search): implement site search suggestions

components/code-example/element.css, components/code-example/prism.css
=> fix(code-example): add prism theme from yari

components/color-theme/controller.js
https://github.com/mdn/fred/commit/dbf60d16afe109bba069c7f61d4ff2eff9513d39 fixed things for the playground but not interactive examples
=> fix(interactive-examples): dark theme now applies on load

components/content-section/server.css
Alternative to https://github.com/mdn/fred/pull/334.
We shouldn't "upgrade" these plain pre tags to code blocks without changes in rari to ensure they have a header, so we don't get content shifts.
So for now, just style them like we do on prod:
=> fix(content-section): style plain pre tags

components/live-sample-result/element.css, components/live-sample-result/element.js, components/playground/element.js, server.js
fix size of header, open play link in new tab, and autorun
proxy assets in dev environment
example: https://fred.review.mdn.allizom.net/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images#art_gallery_example
=> fix(live-samples): assets wouldn't load in playground

components/playground/element.css
applying `display: flex;` to a `<details>` element is only recently supported
so we can't use it
launch this code example in the playground to see (in stable Firefox or Chrome): https://fred.review.mdn.allizom.net/en-US/docs/Learn_web_development/Extensions/Forms/How_to_build_custom_form_controls/Example_5
=> fix(playground): code blocks wouldn't scroll in certain browsers

components/code-example/common.css, components/code-example/element.js, components/content-section/server.css
Examples of good and bad example blocks: http://localhost:3000/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#links
Example of plain `pre` styling which I had to adjust a bit: http://localhost:3000/en-US/docs/Glossary/Base64#base64_characters
=> fix(code-example): highlight good and bad examples

components/not-found/element.css, components/not-found/element.js
- Uses global link styles
- Removes code wrapper from suggested links (they are not code)
=> fix(not-found): use global link styles

components/content-section/server.css
Adds back missing margin for dl > ul that browsers remove for some reason.
=> fix(content-section): add margin to dl > ul

components/left-sidebar/server.css
=> fix(sidebar-filter): highlight was causing weird layouts

components/code-example/prism.css
Also not accessible on yari, so this is an improvement here.
Before:
After:
Contrast check for light and dark mode:
=> fix(syntax-highlighting): ensure comment colour is accessible

components/live-sample-result/element.js, components/play-runner/element.css
Tested on:
- http://localhost:3000/en-US/docs/Web/CSS/Layout_cookbook/Center_an_element#result
- http://localhost:3000/en-US/docs/Web/CSS/Layout_cookbook/Column_layouts#the_recipes
The other page *is* a content issue, it has an absurdly low height set (which rari clamps at 60): https://github.com/mdn/content/blob/main/files/en-us/web/api/media_capture_and_streams_api/taking_still_photos/index.md?plain=1#L286
=> fix(live-sample): don't add px to height if it already has it

components/content-section/server.css
Adds `scroll-margin-top` to `:target` elements within content.
Fixes an issue where clicking e.g. [#autofocus](https://fred.review.mdn.allizom.net/en-US/docs/Web/HTML/Reference/Elements/button#autofocus) scrolls the clicked item behind the page header.
=> fix(content-section): add scroll-margin-top on :target

components/content-section/server.css, components/specifications-list/index.js
Collapses the grouped specification links only if the group has more than one link.
Avoids cases where the specification itself is linked without a text fragment.
Test URLs:
- http://localhost:3000/en-US/docs/Web/HTML/Reference/Global_attributes#specifications
- http://localhost:3000/en-US/docs/Web/CSS/CSS_Values_and_Units#specifications
- http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Operators#specifications
=> fix(specifications-list): collapse only specs with multiple urls

components/curriculum/shared.css
Adds missing background for inline `code` elements.
Yari parity
=> fix(curriculum): add `code` element background

components/content-section/server.css
Anchors in dls:
- Text color
- No underline until hovered
- `#` next to it once hovered
=> fix(content-section): make anchors text color

components/content-section/server.css
=> enhance(content-section): adjust h4-h5 styles

components/modal/element.js, components/search-modal/element.css, entry.client.js, hooks/dialog-closedby.js
the `closedby` attribute on `<dialog>` allows us to close these (including the search) by clicking on the backdrop, but this doesn't work in Firefox Release (only Firefox Nightly). https://github.com/tak-dcxi/dialog-closedby-polyfill fixes this, but it's a bit heavy - and really covers all edge cases, which we don't use - so I cut it down a lot, and included only what we need
Tested in Firefox Release/Nightly and Chrome: would be great to get a test in Safari too
=> fix(search): close when clicking backdrop cross-browser
